### PR TITLE
Update DirectX-Headers to latest

### LINKED ISSUE #5079: Conflict with DirectX-Headers
### Conflict with DirectX-Headers
It's impossible to use DXC with DirectX-Headers on Linux.

### Functional impact
I can't compile project on Linux.

### Minimal repro steps
1. Download DXC release(https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.7.2212.1) and DirectX-Headers(https://github.com/microsoft/DirectX-Headers/releases/tag/v1.608.2)
2. Create CMake project, add DirectX-Headers as subproject and link to DXC
3. Create simple file:
```cpp
#include <unknwn.h>
#include <directx/d3d12shader.h>
#include <dxc/dxcapi.h>

int main() {
    return 0;
}
```
4. Try to compile with clang(version 15.0.7)

### Expected result
It should be possible to use DXC with DirectX-Headers

### Actual result
It doesn't compile.

### Further technical details
Log:
```
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:361:14: error: typedef redefinition with different types ('BYTE' (aka 'unsigned char') vs 'char')
typedef BYTE BOOLEAN;
             ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:38:14: note: previous definition is here
typedef char BOOLEAN;
             ^
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:364:14: error: typedef redefinition with different types ('bool' vs 'uint32_t' (aka 'unsigned int'))
typedef bool BOOL;
             ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:23:46: note: previous definition is here
typedef uint32_t UINT32, UINT, ULONG, DWORD, BOOL, WINBOOL;
                                             ^
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:368:14: error: typedef redefinition with different types ('long' vs 'int32_t' (aka 'int'))
typedef long LONG;
             ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:24:29: note: previous definition is here
typedef int32_t INT32, INT, LONG;
                            ^
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:370:23: error: typedef redefinition with different types ('unsigned long' vs 'uint32_t' (aka 'unsigned int'))
typedef unsigned long ULONG;
                      ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:23:32: note: previous definition is here
typedef uint32_t UINT32, UINT, ULONG, DWORD, BOOL, WINBOOL;
                               ^
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:371:19: error: typedef redefinition with different types ('long long' vs 'int64_t' (aka 'long'))
typedef long long LONGLONG;
                  ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:41:17: note: previous definition is here
typedef int64_t LONGLONG, *PLONGLONG;
                ^
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:372:19: error: typedef redefinition with different types ('long long' vs 'int64_t' (aka 'long'))
typedef long long LONG_PTR;
                  ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:42:17: note: previous definition is here
typedef int64_t LONG_PTR, *PLONG_PTR;
                ^
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:373:28: error: typedef redefinition with different types ('unsigned long long' vs 'uint64_t' (aka 'unsigned long'))
typedef unsigned long long ULONG_PTR;
                           ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:47:18: note: previous definition is here
typedef uint64_t ULONG_PTR, *PULONG_PTR;
                 ^
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:374:28: error: typedef redefinition with different types ('unsigned long long' vs 'uint64_t' (aka 'unsigned long'))
typedef unsigned long long ULONGLONG;
                           ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:39:18: note: previous definition is here
typedef uint64_t ULONGLONG;
                 ^
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:434:16: error: redefinition of '_GUID'
typedef struct _GUID
               ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:101:16: note: previous definition is here
typedef struct _GUID {
               ^
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:448:21: error: 'const' qualifier may not be applied to a reference
typedef const GUID &REFGUID;
                    ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:122:17: note: expanded from macro 'REFGUID'
#define REFGUID const GUID &
                ^
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:448:21: error: typedef redefinition with different types ('const GUID &' (aka 'const _GUID &') vs 'struct _GUID')
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:122:23: note: expanded from macro 'REFGUID'
#define REFGUID const GUID &
                      ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:106:3: note: previous definition is here
} GUID;
  ^
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:448:21: error: expected ';' after top level declarator
typedef const GUID &REFGUID;
                    ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:122:28: note: expanded from macro 'REFGUID'
#define REFGUID const GUID &
                           ^
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:449:21: error: 'const' qualifier may not be applied to a reference
typedef const GUID &REFCLSID;
                    ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:124:18: note: expanded from macro 'REFCLSID'
#define REFCLSID const IID &
                 ^
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:449:21: error: typedef redefinition with different types ('const GUID &' (aka 'const _GUID &') vs 'GUID' (aka '_GUID'))
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:124:24: note: expanded from macro 'REFCLSID'
#define REFCLSID const IID &
                       ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:118:14: note: previous definition is here
typedef GUID IID;
             ^
In file included from /home/keeper/test/main.cpp:2:
In file included from /mnt/project/ThirdParty/dxc/include/dxc/dxcapi.h:37:
/mnt/project/ThirdParty/dxc/include/dxc/WinAdapter.h:449:21: error: expected ';' after top level declarator
typedef const GUID &REFCLSID;
                    ^
/mnt/project/ThirdParty/d3d12/include/wsl/stubs/basetsd.h:124:28: note: expanded from macro 'REFCLSID'
#define REFCLSID const IID &
                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
17 warnings and 20 errors generated.
ninja: build stopped: subcommand failed.

```

### PR DESCRIPTION
**Pull request by amaiorano**
The version being used was from four years ago. Updating to upstream's main broke a lot of code because DirectX-Headers now has the equivalent of WinAdapter.h under `include/wsl` for non-Windows machines, and these collided with DXC's own definitions. I fixed this by including the relevant DirectX-Headers in WinAdapter.h, removed duplicate macros, and adapted some of the existing ones.

Fixes #5079

### CODE REVIEW

**Comment by amaiorano** [comment]
All tests pass, but I will share some questions/concerns:

The types that I removed from WinAdapter.h are because they are already defined in `external/DirectX-Headers/include/wsl/stubs/basetsd.h`. Most of them are effectively the same, but there are some differences:

image

* The `BOOL` type going from `bool` to `uint32_t` might be a concern, especially if used in the public facing API, but I'm not sure.
* `BOOLEAN` was `char` and is now `BYTE` which is `unsigned char`
* The rest went from non-sized types like `int`, `long`, `char`, to sized types like `int32_t`, `int64_t`, `int8_t`, which should be mostly okay on current 32 and 64 bit platforms, except maybe `long`, which went from `long` to `int32_t`. I know that `long` is usually 32-bits on Windows, and 64-bits on Linux (and Mac?).

The next concern to bring up: I don't know if this was the right move, but I modified the root CMakeLists.txt to move the `include_directories` of `DirectX-Headers` paths higher up so that it would be visible to all targets. This allowed me to include one `DirectX-Headers` file, `wsl/winadapter.h`, which ultimately includes other files like `wsl/stubs/basetsd.h`, directly at the top of `WinAdapter.h`. The concern here is that I noticed that `WinAdapter.h` is one of the `install` files in CMake (see `DXC_PLATFORM_PUBLIC_HEADERS` in `include/dxc/CMakeLists.txt`). So this file was meant to be a standalone includable file, so I'm not sure if this will work for users of an installed DXC (I don't think there are any tests for this scenario). Users of DXC would also need `DirectX-Includes` and add `DirectX-Headers/include` to their include directories. Is this okay? If not, what should be done?

**Comment by amaiorano** [comment]
I did a bit more digging to understand the root of what changed in `DirectX-Headers`. Basically:

In old DirectX-Headers:

`wsl/stubs` really contains only stubs. For example, `external/DirectX-Headers/include/wsl/stubs/rpcndr.h` was basically empty.

`external/DirectX-Headers/include/wsl/winadapter.h` did contain Windows types for non-Windows, but this file was not included in DXC.

In latest DirectX-Headers:

`wsl/stubs` are no longer really stubs. Now `external/DirectX-Headers/include/wsl/stubs/rpcndr.h` defines `__CRT_UUID_DECL` and includes `external/DirectX-Headers/include/wsl/stubs/basetsd.h` (also in stubs) which is where most of what was in `external/DirectX-Headers/include/wsl/winadapter.h` has moved to.

A concrete example of a build error we get when updating DirectX-Headers:

Building `lib/DxilContainer/CMakeFiles/LLVMDxilContainer.dir/D3DReflectionStrings.cpp.o` fails because of the inclusion chain:
```
lib/DxilContainer/D3DReflectionStrings.cpp
  include/dxc/Test/D3DReflectionStrings.h
    include/dxc/Support/D3DReflection.h
      external/DirectX-Headers/include/directx/d3d12shader.h
        external/DirectX-Headers/include/directx/d3dcommon.h
          external/DirectX-Headers/include/wsl/stubs/rpcndr.h
            external/DirectX-Headers/include/wsl/stubs/basetsd.h
```

If we comment out the include of  d3d12shader.h in D3DReflection.h, then we get compile errors because of unknown enums:
```
/home/amaiorano/src/external/DirectXShaderCompiler/include/dxc/Test/D3DReflectionStrings.h:24:17: error: unknown type name 'D3D_CBUFFER_TYPE'
   24 | LPCSTR ToString(D3D_CBUFFER_TYPE CBType);
      |                 ^
/home/amaiorano/src/external/DirectXShaderCompiler/include/dxc/Test/D3DReflectionStrings.h:25:17: error: unknown type name 'D3D_SHADER_INPUT_TYPE'
   25 | LPCSTR ToString(D3D_SHADER_INPUT_TYPE Type);
      |                 ^
```

I thought of maybe "disabling" the ultimate inclusion of "basetsd.h" by defining the header guard, but unfortunately this file doesn't use a classic header guard, but uses #pragma once. When I delete the contents of the file locally just to test, I am able to compile D3DReflectionStrings.cpp.

In fact, if I delete the contents of "basetsd.h", and "rpcndr.h", but make sure to `#define __RPCNDR_H_VERSION__` before including d3d headers, all of dxc builds.

So I'm not really seeing a way out of this that's much different from the change I've put up here. As I wrote in my previous comment, users of DXC on Linux/Mac would need `DirectX-Includes` and add `DirectX-Headers/include/wsl/stubs` to their include directories.

File: include/dxc/WinAdapter.h [hunk 1]
```diff
@@ -220,21 +232,9 @@
...
-#define E_NOINTERFACE (HRESULT)0x80004002
-#define E_NOTIMPL (HRESULT)0x80004001
 #define E_NOT_VALID_STATE (HRESULT)0x8007139F
-#define E_OUTOFMEMORY (HRESULT)0x8007000E
-#define E_POINTER (HRESULT)0x80004003
-#define E_UNEXPECTED (HRESULT)0x8000FFFF
 
-#define SUCCEEDED(hr) (((HRESULT)(hr)) >= 0)
-#define FAILED(hr) (((HRESULT)(hr)) < 0)
 #define DXC_FAILED(hr) (((HRESULT)(hr)) < 0)
```
Comment (damyanp) [inline include/dxc/WinAdapter.h:238]: Does DXC_FAILED still need to exist?

File: include/dxc/WinAdapter.h [hunk 2]
```diff
@@ -220,21 +232,9 @@
 #define S_OK ((HRESULT)0L)
 #define S_FALSE ((HRESULT)1L)
 
-#define E_ABORT (HRESULT)0x80004004
-#define E_ACCESSDENIED (HRESULT)0x80070005
 #define E_BOUNDS (HRESULT)0x8000000B
```
Comment (damyanp) [inline include/dxc/WinAdapter.h:235]: Presumably the defines removed here conflicted with ones in DirectX headers?  Are the remaining ones still required?

File: include/dxc/WinAdapter.h [hunk 3]
```diff
@@ -560,26 +441,9 @@ template <typename T> inline void **IID_PPV_ARGS_Helper(T **pp) {
...
-struct IUnknown {
-  IUnknown(){};
-  virtual HRESULT QueryInterface(REFIID riid, void **ppvObject) = 0;
-  virtual ULONG AddRef() = 0;
-  virtual ULONG Release() = 0;
-  template <class Q> HRESULT QueryInterface(Q **pp) {
-    return QueryInterface(__uuidof(Q), (void **)pp);
-  }
-};
+// Note: IUknown UUID is defined in DirectX-Headers
```
Comment (damyanp) [inline include/dxc/WinAdapter.h]: Typo, although my preference would be to remove this comment, IMO this detail is only interesting the context of this PR.

```suggestion
// Note: IUnknown UUID is defined in DirectX-Headers
```

**Review by damyanp — COMMENTED** [review]
I've left a few questions.  I think that the main thing we need to figure out is how do we convince ourselves that this change doesn't break anything?  Is it enough that the build pipelines pass?  Do we need to do some manual live testing on non-Windows systems?

@tex3d, @jenatali, do you have any thoughts here?

**Comment by jenatali** [comment]
This looks right to me. The `DirectX-Headers` definitions mean that datatypes and behaviors will be the same across Windows and Linux so I think standardizing on that is the right call even if it's different than how they were defined before. I'm not sure how thorough the tests are for the Linux builds, but as long as we can compile some basic shaders I suspect that this change would be fine.

> So I'm not really seeing a way out of this that's much different from the change I've put up here. As I wrote in my previous comment, users of DXC on Linux/Mac would need DirectX-Includes and add DirectX-Headers/include/wsl/stubs to their include directories.

I don't have a great answer here but at least for now this seems okay?

**Comment by amaiorano** [comment]
> I've left a few questions. I think that the main thing we need to figure out is how do we convince ourselves that this change doesn't break anything? Is it enough that the build pipelines pass? Do we need to do some manual live testing on non-Windows systems?

I suspect it may break projects that depend on an installed DXC on non-Windows as they would now need to also depend on DirectX-Headers (and add it to their include path). I think projects that use CMake `add_subdirectory` should work out of the box. It would be nice to test these cases, I'm just not sure where to look.

I can at least make sure this new dep on DirectX-Headers is clearly stated in the commit comment, which may help downstream users of DXC.

File: include/dxc/WinAdapter.h (hunk 1 above)
Comment (amaiorano) [reply include/dxc/WinAdapter.h:238]: It's used in a few places. It could be removed and replaced with `FAILED`, but that should be done in a follow-up change, I think.

File: include/dxc/WinAdapter.h (hunk 2 above)
Comment (amaiorano) [reply include/dxc/WinAdapter.h:235]: Yes and yes. Both `E_BOUNDS` and `E_NOT_VALID_STATE` are used in the DXC codebase, but are not defined in `wsl/stubs/basetsd.h` (DirectX-Includes).

File: include/dxc/WinAdapter.h (hunk 3 above)
Comment (amaiorano) [reply include/dxc/WinAdapter.h]: Will remove.

**Comment by damyanp** [comment]
So by "use dxc" here, I think we mean people who are compiling and linking against the DXC libraries? This doesn't impact anyone who just installs a binary release of dxc, right?

> I suspect it may break projects that depend on an installed DXC on non-Windows as they would now need to also depend on DirectX-Headers (and add it to their include path). 

Would also break people including it as a submodule?


>I think projects that use CMake `add_subdirectory` should work out of the box. It would be nice to test these cases, I'm just not sure where to look.

Will this mean that the vcpkg maintainers will need to react to this change as well?

**Comment by amaiorano** [comment]
> So by "use dxc" here, I think we mean people who are compiling and linking against the DXC libraries? This doesn't impact anyone who just installs a binary release of dxc, right?

Yes.

> Would also break people including it as a submodule?

I think by this you mean using `add_subdirectory` in CMake, which I think will work.

> Will this mean that the vcpkg maintainers will need to react to this change as well?

Good question.

What I'm going to do is test different scenarios on Linux:

1. Simple CMake project that uses an "install" of DXC (adds `dxc/include` to path).
2. CMake project that depends on DXC using add_subdirectory (we actually do this in Dawn, but it's [not easy](https://dawn.googlesource.com/dawn/+/refs/heads/main/third_party/CMakeLists.txt#239).
3. Project that consumes DXC via vcpkg.

As a side note, I tried building with gcc and got a bunch of warnings similar to those I got with Clang, so I'll add some pragmas to ignore them like I did for Clang.

**Comment by tex3d** [comment]
In the past, we have intended to include all the (non-std) headers required to use the API in our GitHub release package. With this change, as mentioned, you must separately get and include at least `basestd.h` from DirectX-Headers.

Dependencies on DirectX-Headers were originally meant only for the DXC execution tests. DirectX headers weren't meant to be required by users of the DXC API, and developers who acquire the API through the GitHub release package might not be happy with a new project dependency just for a new 12k header that supplies a few definitions that used to be independently declared.

Maybe we could add this header to our GitHub release package to avoid any additional project dependencies when using the DXC API from that package. We could put it under another folder matching DirectX-Headers sub-path structure so it can easily be used as an include path instead of the full DirectX_headers, when minimal dependencies are desired. Otherwise, it seems excessive to add the whole DirectX-Headers project dependency just to include a 12k header.

Alternatively, we could move all our DXC API headers to the `DirectX-Headers` project, and no longer package them in the GitHub release packages. Then force everyone to get all the DXC API headers form DirectX-Headers for future releases.

**Comment by amaiorano** [comment]
> Dependencies on DirectX-Headers were originally meant only for the DXC execution tests. DirectX headers weren't meant to be required by users of the DXC API, and developers who acquire the API through the GitHub release package might not be happy with a new project dependency just for a new 12k header that supplies a few definitions that used to be independently declared.

Yes, I agree, and it's why I raised this concern above.

> Maybe we could add this header to our GitHub release package to avoid any additional project dependencies when using the DXC API from that package. We could put it under another folder matching DirectX-Headers sub-path structure so it can easily be used as an include path instead of the full DirectX_headers, when minimal dependencies are desired. Otherwise, it seems excessive to add the whole DirectX-Headers project dependency just to include a 12k header.

I think this is a good idea, and would cause the least friction - at least in the short term. If I understand correctly, you're saying that users of the DXC API would have to update their include path no matter what: either to
1. Include the new sub-path structure now available in the installed DXC directory;
2. Or include the one from DirectX-Headers.

This would be a breaking change, no matter what, for all users of the DXC API; however, we provide an easy way out for non-`DirectX-Headers` users: add an extra include path.

If this is what you mean, and others agree with this, I could modify my PR to do this (add the copying of files needed to the CMake install target, add a comment at the top of WinAdapter.h explaining this, and updating the commit message as well).
