### PR TITLE
Fix StringRef build failure with newer libc++

### LINKED ISSUE #8306: DirectXShaderCompiler vendored in SDL_shadercross fails to build with Xcode 26.4 / Apple clang 21 on macOS
Hi,
I am hitting a build failure in the vendored external/DirectXShaderCompiler when building SDL_shadercross on macOS with the current Xcode. I have replaced the with the current head from microsoft/DirectXShaderCompiler but that did not fix the issue.

Environment:
- macOS on Apple Silicon
- Xcode 26.4
- Apple clang 21.0.0
- SDK: MacOSX26.4.sdk
- SDL_shadercross [3a31448](https://github.com/libsdl-org/SDL_shadercross/commit/3a314481ede01f5d966f0e834019942e34c02b82)
- DirectXShaderCompiler [67a8e24](https://github.com/microsoft/DirectXShaderCompiler/commit/67a8e24c8dd26c3df3e8389cbdf412690dab57e6)

I have SDL_shadercross vendored in my game engine. The build fails while compiling vendor/SDL_shadercross/external/DirectXShaderCompiler/... sources, with errors coming from include/llvm/ADT/StringRef.h.
Representative error:
```
/Users/frank/Projects/bms/adventurer/vendor/SDL_shadercross/external/DirectXShaderCompiler/include/llvm/ADT/StringRef.h:579:10: error: 'is_nothrow_constructible' cannot be specialized: Users are not allowed to specialize this standard library entity [-Winvalid-specialization]
  579 |   struct is_nothrow_constructible <std::string, llvm::StringRef>
      |          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.4.sdk/usr/include/c++/v1/__type_traits/is_nothrow_constructible.h:23:8: note: marked '_Clang::no_specializations' here
   23 | struct _LIBCPP_NO_SPECIALIZATIONS is_nothrow_constructible
      | 
```
I see the same error for:
- is_nothrow_constructible<std::string, llvm::StringRef>
- is_nothrow_constructible<std::string, llvm::StringRef &>
- is_nothrow_constructible<std::string, const llvm::StringRef &>
This appears to be caused by newer libc++ in Xcode 26.4 rejecting specialization of this standard library trait.

Full log: https://pastebin.com/XKX67V5N

### PR DESCRIPTION
**Pull request by tsukinoko-kun**
Fixes #8306.
## Summary
Building DXC with newer Apple toolchains fails in `include/llvm/ADT/StringRef.h` because libc++ now rejects user specializations of certain standard library traits. DXC currently specializes:
- `std::is_nothrow_constructible<std::string, llvm::StringRef>`
- `std::is_nothrow_constructible<std::string, llvm::StringRef &>`
- `std::is_nothrow_constructible<std::string, const llvm::StringRef &>`
On Xcode 26.4 / Apple clang 21 / libc++, that now produces an error like:
> `is_nothrow_constructible` cannot be specialized: Users are not allowed to specialize this standard library entity
## What this changes
This patch keeps the existing HLSL workaround for non-libc++ standard libraries, but disables those `std::is_nothrow_constructible` specializations when building against libc++:
```cpp
#if !defined(_LIBCPP_VERSION)
...
#endif
```
Why this fixes the issue
The failure is caused by the specializations themselves, not by any runtime behavior in StringRef.
For libc++:
- the specializations are now ill-formed and rejected at parse time
- libc++ already computes std::is_nothrow_constructible<std::string, llvm::StringRef> correctly without the workaround
So the fix is to stop declaring the forbidden specialization on libc++, while preserving the existing behavior everywhere else.
Why I chose this approach
I looked at the HLSL-specific block in StringRef.h and tested the current Apple libc++ behavior directly. Without the manual specialization, libc++ still reports the relevant is_nothrow_constructible cases as false, which matches the intent of the original workaround.
That made this the narrowest safe fix:
- it resolves the Xcode/libc++ build break in #8306
- it does not change runtime code generation or ABI
- it preserves the original workaround for non-libc++ environments where it may still be needed
Validation
I verified:
- the original header fails to compile with current Xcode/libc++
- after this change, the header compiles cleanly
- on libc++, the relevant std::is_nothrow_constructible instantiations still evaluate to false

### CODE REVIEW

**Comment by pow2clk** [comment]
@damyannp I agree with the argument made in #8303 that the static asserts ensure that, on all currently supported compilers, the static asserts verify that this explicit manipulation isn't required anymore. I tested my own fix very similar to that approach on VS 2017 and others and found no issues. Maybe @tex3d remembers the history here.

That said, at this point, the compiler will not build on macos, so this or something similar really needs to go in. I have my own fix with a couple new mac compiler warnings fixed too here if you're interested https://github.com/pow2clk/DirectXShaderCompiler/commit/ea596b1a77215d0b6a3fbe92ee803abda6b8be1e

**Comment by bogner** [comment]
Do we need to keep the workaround for non-libc++ standard libraries? The comments in #8303 strongly suggest we can just remove this completely.

**Comment by damyanp** [comment]
> Do we need to keep the workaround for non-libc++ standard libraries? The comments in #8303 strongly suggest we can just remove this completely.

Maybe the test added in https://github.com/minchopaskal/DirectXShaderCompiler/commit/990328694428d8728fbb25bdea1c7c5a65c92543#diff-2f6bf948cfb0de9574a698d2a6fc79359d333c73fb62a9d357ace4bc2d86a4c3 would be enough to give us confidence?

**Comment by tsukinoko-kun** [comment]
I suggest fixing compiler errors first, then later removing workarounds. I don't care if you use my PR or any other fix.
It's a "make it work again ASAP" without breaking anything.

**Review by bob80905 — APPROVED** [review]

**Comment by tsukinoko-kun** [comment]
The required microsoft.DirectXShaderCompiler check seems to be stuck in ‘Expected — Waiting for status to be reported’. Could a maintainer please trigger/re-run the Azure pipeline?

**Comment by tsukinoko-kun** [comment]
Hey, can this PR be merged? If you want me to do anything beforehand, please let me know.

**Review by bogner — APPROVED** [review]
I don't understand why we don't just delete this code completely (like in #8303, which I think was a better fix). This isn't *wrong* though, so I suppose it's fine.
